class ErrorCode:
    AUTHENTICATION_REQUIRED = "Authentication required."
    AUTHORIZATION_FAILED = "Authorization failed. User has no access."
    INVALID_TOKEN = "Invalid token."
    INVALID_CREDENTIALS = "Invalid credentials."
    EMAIL_TAKEN = "Email is already taken."
    USERNAME_TAKEN = "Username is already taken."
    USER_NOT_FOUND = "User not found."
    USER_NOT_CREATED = "User not created."
    REFRESH_TOKEN_NOT_VALID = "Refresh token is not valid."
    REFRESH_TOKEN_REQUIRED = "Refresh token is required either in the body or cookie."
    PASSWORD_NOT_MATCHED = "Old password is wrong."
    INVALID_EMAIL = "No user is using this email address."
    INVALID_RESET_TOKEN = "Invalid reset token."
    RESET_TOKEN_EXPIRED = "Reset token is expired."
